### ISSUE TITLE
[BUG] The better player needs to update dependencies visibility_detector ^0.3.3

### ISSUE THREAD

**Issue by RoyalCoder88** [jhomlala/betterplayer#1004]
The better player needs to update dependencies:

`Because better_player >=0.0.80 depends on visibility_detector ^0.2.2 and unipeople depends on visibility_detector ^0.3.3, better_player >=0.0.80 is forbidden.
So, because app depends on better_player ^0.0.82, version solving failed.
pub get failed (1; So, because app depends on better_player ^0.0.82, version solving failed.)
exit code 1`

Thanks in advance!

**Comment by ciriousjoker** [comment]
@jhomlala This can be closed, it was fixed in `v0.0.83`.

**Comment by ashishazilen** [comment]
Because better_player >=0.0.83 depends on xml ^6.1.0 and flutter_svg >=0.21.0-nullsafety.0 <1.1.0 depends on xml ^5.0.0, better_player >=0.0.83 is incompatible with flutter_svg >=0.21.0-nullsafety.0 <1.1.0.
And because flutter_html 2.2.1 depends on flutter_svg >=0.22.0 <1.0.0 and no versions of flutter_html match >2.2.1 <3.0.0, better_player >=0.0.83 is incompatible with flutter_html ^2.2.1.
So, because kaptivate depends on both flutter_html ^2.2.1 and better_player ^0.0.83, version solving failed.
pub get failed (1; So, because kaptivate depends on both flutter_html ^2.2.1 and better_player ^0.0.83, version solving failed.)
exit code 1

**Comment by ashishazilen** [comment]
@ciriousjoker can u plz help with my above issue?
