### ISSUE TITLE
 Help using subtitles from an .mkv file

### ISSUE THREAD

**Issue by renanbalthazar** [jhomlala/betterplayer#105]
Player is very good, simply the best I found to use. But I still haven't figured out how to use a caption that is embedded in an .mkv file.

thank you.

**Comment by jhomlala** [comment]
@renanbalthazar Unfortunately, AVPlayer, which is used by Better Player can't play MKV files. Since we can't play this file on iOS, I won't add special support for subtitles. https://stackoverflow.com/questions/39045903/play-mkv-video-from-remote

On Android you can play this format, because it's supported by ExoPlayer.
