### ISSUE TITLE
[BUG] IOS 17 - Duration of video stuck at 00

### ISSUE THREAD

**Issue by awnigharbia** [jhomlala/betterplayer#1258]
After IOS 17 update. I started to notice some videos have stuck at zero duration of video and everytime you pause and start the video it reset the playback from beginning.

As you can see like this:

<img width="525" alt="Screenshot 2023-09-22 at 2 01 50 AM" src="https://github.com/AnonymHK/betterplayer/assets/13357658/cecd09ea-34ab-4b24-852c-e0567e65e4c4">

Any help would be appreciated.

**Comment by n0m4dz** [comment]
Same issues in ios17

**Comment by awnigharbia** [comment]
I found a paid solution dm me for info.

**Comment by erindolson** [comment]
What worked for me: 

In BetterPlayer.m in (void)onReadyToPlay
---         if (_player.status != AVPlayerStatusReadyToPlay) {
+++       if (_player.currentItem.status != AVPlayerItemStatusReadyToPlay || _player.status != AVPlayerStatusReadyToPlay) {

It's probably more of a bandaid than fixing the root problem. There's some race condition with checking the duration of the AVPlayerItem before the AVPlayerItem is is ready to be played (stated [here](https://developer.apple.com/documentation/avfoundation/avplayeritem/1389386-duration) to not check duration before status ready) that is exposed in iOS17. 

The real problem might be more related to the fact that this if doesn't check if AVPlayerItem's status is ready. 
```
else if (context == presentationSizeContext){
        [self onReadyToPlay];
    }
```

I don't know enough about the video player stuff to say for sure where the root cause is.

**Comment by RonakPustack** [comment]
Why was this issue closed?
What is the permanent solution?

**Comment by RonakPustack** [comment]
Why was this issue closed?
What is the permanent solution?

**Comment by M1314** [comment]
The issue of the player still persists. But you can handle the problem in the platform waiting for it to be ready with something similar to:

       void _startVideoInitializationCheck(
         BetterPlayerController controller,
         int requestId, {
         required int restorePositionMs,
         }) {
         int attempts = 0;
         const maxAttempts = 120;
         Timer.periodic(const Duration(milliseconds: 100), (timer) {
         if (!mounted ||
           requestId != _resourcePreparationRequestId ||
           _videoController != controller) {
           timer.cancel();
          `` return;
         }

      final videoPlayerController = controller.videoPlayerController;
      final value = videoPlayerController?.value;
      final duration = value?.duration;
      final hasDuration = duration != null && duration > Duration.zero;
      final isReady = value != null && value.initialized && hasDuration;

      if (isReady) {
        timer.cancel();
        if (restorePositionMs > 0) {
          final durationMs = duration.inMilliseconds;
          final clampedPositionMs = restorePositionMs.clamp(0, durationMs);
          try {
            controller.seekTo(Duration(milliseconds: clampedPositionMs));
          } catch (_) {}
        }
        if (mounted && requestId == _resourcePreparationRequestId) {
          setState(() {
            _isVideoReady = true;
            _videoInitFailed = false;
          });
        }
        return;
      }
      attempts++;
      if (attempts >= maxAttempts) {
        timer.cancel();
        if (mounted && requestId == _resourcePreparationRequestId) {
          setState(() {
            _videoInitFailed = true;
          });
        }
      }
    });
  }
