### ISSUE TITLE
Better Directional Pad Support

### ISSUE THREAD

**Issue by YaarPatandarAA** [jhomlala/betterplayer#212]
**Is your feature request related to a problem? Please describe.**

- Currently the controls kind of work with a directional pad. 
- When a video is started no control is in focus, must move on directional pad to focus on a control.
- Clicking the ok/select/center button on a directional pad doesn't bring up the controls. However if a control is in focus (and controls are hidden) clicking the ok/select/center button will execute the control which was in focus and bring up the controls.
- BIGGEST ISSUE: Directional pad is unable to focus on progress bar indicator, this is needed to seek in the video.

**Describe the solution you'd like**

- Better support of directional pads, on default controls.

**Describe alternatives you've considered**

- Using the controls builder to build own controls.

**Additional context**

- Would rather use the default controls as they accomplish what I need. 
- I am using this package to build an Android TV application.

You can use the Android TV Emulator and its built in Directional Pad to test controls.

Thanks

**Comment by jhomlala** [comment]
Right now Android TV Emulator doesn't support firing center button: https://stackoverflow.com/questions/64624422/android-tv-emulator-keycode-dpad-center-event-not-dispatched

I'm unable to do that right now due to lack of tv which supports Android TV. Anyway feel free to create PR :) I'll appreciate it!

Just small tip: you can add custom player control to Better Player. Maybe that will help building tv-supported controls.
