### ISSUE TITLE
[FEATURE] Ability to restart the player when started without internet

### ISSUE THREAD

**Issue by MiroLiebschner** [jhomlala/betterplayer#238]
When no internet is available while the player is started then the player shows the error message and is no longer usable. 

In my opinion there should be a method to restart the player so it is more user-friendly. Perfect would be if the player autostart as soon as internet is available or a method to "try again"

**Comment by jhomlala** [comment]
If you want to provide restart ability when connection is back active, you can do it easily with this package: https://pub.dev/packages/connectivity

Just listen to the connectivity state and when connection is back online just set data source again in given controller. This will reload better player. You can always check if better player controller reports error (event listener) and check if it's buffering. There are many possibilites to handle this state. You can even set position of the player after restart to have best UX.

I don't want to include anymore 3rd party plugins since they are very often breaking building of the apps. The less 3rd party plugins then it's better. This feature won't be implemented.

**Comment by MiroLiebschner** [comment]
Alright seems like  I was just unable to find the correct way to do it. Thank you for helping :)
