### ISSUE TITLE
[FEATURE] WEB support

### ISSUE THREAD

**Issue by BartusZak** [jhomlala/betterplayer#369]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm not able to use packages on all platforms that Flutter supports 👯 

**Describe the solution you'd like**
I would like to know If is it possible to use that package for WEB.

**Describe alternatives you've considered**
There is no alternatives for WEB support for `HLS` and calculate headers per single `.aac` file.

**Additional context**
Ther is no additional context.

**Comment by jhomlala** [comment]
See https://github.com/jhomlala/betterplayer/issues/142

I don't have enough time to support all platforms since it requires tremendous amount of work. I'm working on it in my spare time for free, so I don't see any options to add it in near future. Right now I'm focusing on stabilisation of Android and iOS versions which also takes a lot of time and energy.

Anyway I'm open for contribution. Feel free to open PR @BartusZak. I will appreciate it!
