### ISSUE TITLE
It's crashing all over IOS, how it's supposed to be better ?

### ISSUE THREAD

**Issue by danielwalczak** [jhomlala/betterplayer#41]

**Comment by leszekkrol** [comment]
2020-07-23 15:31:45.159345+0200 Runner[28300:413281] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <FLTVideoPlayer 0x600003d56800> for the key path "status" from <AVPlayerItem 0x60000114cfd0> because it is not registered as an observer.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   Foundation                          0x00007fff259114ff -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 601
	3   Foundation                          0x00007fff2591190d -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 74
	4   Foundation                          0x00007fff2591183a -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:context:] + 177
	5   better_player                       0x0000000105864cd2 -[FLTVideoPlayer disposeSansEventChannel] + 130
	6   better_player                       0x0000000105864ec4 -[FLTVideoPlayer dispose] + 36
	7   better_player                       0x0000000105866efb __48-[FLTVideoPlayerPlugin handleMethodCall:result:]_block_invoke + 75
	8   libdispatch.dylib                   0x00000001068bee8e _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00000001068c17a3 _dispatch_continuation_pop + 552
	10  libdispatch.dylib                   0x00000001068d4b2c _dispatch_source_invoke + 2205
	11  libdispatch.dylib                   0x00000001068ccbce _dispatch_main_queue_callback_4CF + 692
	12  CoreFoundation                      0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x00007fff23d9c3b9 __CFRunLoopRun + 2041
	14  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	15  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	16  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	17  Runner                              0x0000000102d9fe3b main + 75
	18  libdyld.dylib                       0x00007fff520ce1fd start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by leszekkrol** [comment]
@jhomlala Any update in this topic?

**Comment by jhomlala** [comment]
Thanks for your report, it's fixed.

**Comment by cyborgfeep** [comment]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(0x1a100d9d8 0x1b5376b54 0x1a0f198f4 0x1053cca84 0x1053cc874 0x1053cce80 0x1a229b6c4 0x1a229daf8 0x1a229aef0 0x1a85432e0 0x1054f3ce4 0x1054f5528 0x105503994 0x1a0f8d5e0 0x1a0f87a88 0x1a0f86ba0 0x1b7cc4598 0x1a38763d8 0x1a387b958 0x10297f300 0x1a0c65568)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
terminating with uncaught exception of type NSException

**Comment by Ibrokhim98** [comment]
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
> *** First throw call stack:
> (0x1a100d9d8 0x1b5376b54 0x1a0f198f4 0x1053cca84 0x1053cc874 0x1053cce80 0x1a229b6c4 0x1a229daf8 0x1a229aef0 0x1a85432e0 0x1054f3ce4 0x1054f5528 0x105503994 0x1a0f8d5e0 0x1a0f87a88 0x1a0f86ba0 0x1b7cc4598 0x1a38763d8 0x1a387b958 0x10297f300 0x1a0c65568)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
> terminating with uncaught exception of type NSException

Did you find any solution to this bug. I have the same error in iOS when trying to seek video, it is crashing the app.

**Comment by Ibrokhim98** [comment]
> > *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
> > *** First throw call stack:
> > (0x1a100d9d8 0x1b5376b54 0x1a0f198f4 0x1053cca84 0x1053cc874 0x1053cce80 0x1a229b6c4 0x1a229daf8 0x1a229aef0 0x1a85432e0 0x1054f3ce4 0x1054f5528 0x105503994 0x1a0f8d5e0 0x1a0f87a88 0x1a0f86ba0 0x1b7cc4598 0x1a38763d8 0x1a387b958 0x10297f300 0x1a0c65568)
> > libc++abi.dylib: terminating with uncaught exception of type NSException
> > *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
> > terminating with uncaught exception of type NSException
> 
> Did you find any solution to this bug. I have the same error in iOS when trying to seek video, it is crashing the app.

@jhomlala any solution for this bug?
