### ISSUE TITLE
App crashes on OOM when there are multiple players in a list view (version 0.0.71 and up)

### ISSUE THREAD

**Issue by shimaatech** [jhomlala/betterplayer#641]
My app has a list view with video players, it was working well with version 0.0.69 and it works well with 0.0.70 also, but when I move to version 0.0.71 or 0.0.72 then it crashes on OOM after playing some videos

**Comment by shimaatech** [comment]
actually even with 0.0.70 it crashes also but with lower frequency.
0.0.69 works perfectly

**Comment by jhomlala** [comment]
@shimaatech Please provide reproducible example. I need to reproduce it on my device.

**Comment by jhomlala** [comment]
OOM issues are happening because you're trying to use multiple BP instances without clearing previous instances. There're 2 things you can do to solve your problem:
* Use reusable video list: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list
* Lower buffering configuration, for example:
```dart
bufferingConfiguration: BetterPlayerBufferingConfiguration(minBufferMs: 2000, maxBufferMs: 10000,bufferForPlaybackMs: 1000, bufferForPlaybackAfterRebufferMs: 2000)
```
`bufferingConfiguration` is parameter in `BetterPlayerDataSource`.
