### ISSUE TITLE
[BUG] Can't compile iOS

### ISSUE THREAD

**Issue by CripyIce** [jhomlala/betterplayer#776]
**Describe the bug**
Trying to build my project and I get the following error:
```bash
    /Users/eitanaflalo/development/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.77/ios/Classes/CacheManager.swift:121:62: error: value of optional type 'Data?' must be unwrapped to a value of type 'Data'
                        playerItem = CachingPlayerItem(data: data!, mimeType: mimeTypeResult.1, fileExtension: mimeTypeResult.0)
```

**To Reproduce**
1. Add the library to the project
2. Compile for iOS

**Flutter doctor**
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (3 available)

• No issues found!
```

**Better Player version**
- Version:

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 13
 - OS: iOS 15.0

**Comment by adrianvintu** [comment]
Any estimates when this will work?

**Comment by jhomlala** [comment]
@adrianvintu please don't ask for estimate and read this: https://github.com/jhomlala/betterplayer/issues/702

To anyone who's having problem:
From my perspective everything is fine with BP. There's issue with your project configuration. 
* Please check if error happens on clear project. Create clear project and add BP dependency.
* Try to remove other dependencies to see which collide with Better Player.
* If nothing helps, please provide reproducible example.

Here's more details: https://github.com/jhomlala/betterplayer/issues/714

I'm able to help only if you will provide reproducible example.

**Comment by barees63** [comment]
I'm pretty rusty on Swift atm but if I change:

`playerItem = CachingPlayerItem(data: data!, mimeType: mimeTypeResult.1, fileExtension: mimeTypeResult.0)
`

to

`playerItem = CachingPlayerItem(data: data!!, mimeType: mimeTypeResult.1, fileExtension: mimeTypeResult.0)
`

It compiles fine.  I also noticed in other projects (eg. the example for Better Player) I don't have this issue.  FWIW My project is set to target iOS 13.0

**Comment by jhomlala** [comment]
Changing example project target to iOS 13.0 didn't trigger this issue on my side. In order to fix this issue I need reproducible example.

**Comment by jblough** [comment]
From a Swift perspective, would it be preferred to write
```
            // Trying to retrieve a track from cache syncronously
            let data = try? storage?.object(forKey: _key)
            if data != nil {
```
as
```
            // Trying to retrieve a track from cache synchronously
            if let data = try? storage?.object(forKey: _key) {
```
on line 112 of CacheManager.swift ?

**Comment by obrunsmann** [comment]
Have the same issue. I first thought that it's because we're on swift 4 so I migrated to a fresh swift 5 project. Still the same issue.

```
/Users/oliver/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.79/ios/Classes/CacheManager.swift:121:63: error: cannot force unwrap value of non-optional type 'Data'
```

Adding a `!!` from https://github.com/jhomlala/betterplayer/issues/776#issuecomment-955787266 solves the issue temporarily.

**Comment by obrunsmann** [comment]
@jhomlala the reason is actually what I wrote before. So our project was on Swift 4, migration to Swift 5 **solved the problem**. 

Please add some note to the package that only Swift 5 projects are supported or don't use optional try for Swift 4 support; this costs hours of debugging, especially for these guys, having no experience in swift.

**Solution for anyone having the same problem:**
You might see this if you have created a flutter 1 project. You can check your project's swift version here:
![image](https://user-images.githubusercontent.com/763812/144703046-bd5f0e1d-cc43-49f4-b7f4-0a37bb3e40e2.png)

What I did to upgrade to latest flutter iOS scaffold:

```bash
cd projectfolder
rm -rf ios/
flutter create --platforms=ios .
```

Just check the basic settings like package identifier, certificates and app icon (by the way, suggest the following so that you have no effort: https://pub.dev/packages/flutter_launcher_icons) and then you're ready with swift 5.

Credits to @mitghi for the solution

**Comment by jhomlala** [comment]
I've added info about Swift 5. Thanks for reporting.
