### ISSUE TITLE
Add support for play a file with bytes array

### ISSUE THREAD

**Issue by SaliBhdr** [jhomlala/betterplayer#89]
In some cases, we need to manipulate the bytes array of a file. Some cases like purchasable online courses. I don't want the user to be able to use the file outside of my app. So what I do is encrypt the file's byte array and save the file with a new extension.
After that when the client wants to play the file in the video player, At the moment what I had to do is read the file, decrypt it and save a temp file to pass to the video player with the correct format. But in Android exo-player, there is a feature that you can pass chunks of bytes array to the player, and the exo-player plays the video byte by byte. So if the player support bytes array in a stream, there is no need to save a temp file and risk file exposure.

It would be great to have such a feature in flutter too.

**Comment by jhomlala** [comment]
@SaliBhdr 
Seems like it's doable with ExoPlayer, but how about iOS and AVPlayer? From my research it's seems to be tricky stuff to play from memory. P

**Comment by SaliBhdr** [comment]
@jhomlala Could you please explain why it can't be doable in IOS? I don't have much experience in IOS.

**Comment by jhomlala** [comment]
@SaliBhdr Flutter plugin should have consistent behavior across all platforms. If something is not possible on iOS, I won't implement it on Android too. If you want only android behavior you can fork Better Player and this behavior for your purpose.

I couldn't find any informations about playing some array of bytes on iOS player (AVPlayer), so I will not proceed with Android (ExoPlayer) only implementation.

If you have any useful information about playing array of bytes on iOS please provide it in this issue. Otherwise I will close it.

**Comment by bdlukaa** [comment]
You can hack it a little bit. You can implement it, so in Android you will use the ExoPlayer solution and in Ios you can use this solution: https://stackoverflow.com/questions/45700189/not-able-to-read-back-the-audio-binary-data-from-realm-db-to-play-with-avplayer

**Comment by jhomlala** [comment]
Added memory data source in 0.0.34.

**Comment by lemkoleg** [comment]
Hello. I have an application that downloads encoded media files from a server.
The application controls which parts of the file have already been downloaded and downloads the necessary ones to complete the puzzle.
The application pre-creates a dummy file of the required size, and simply replaces the received fragments
to the corresponding fragments in the file.
Is it possible to intercept, by my application, a request to read this file from applications (for example, from AVPlayer),
in order to check if this fragment of the file (or part of the fragment) is loaded and return only those bytes of the fragment,
which are considered already loaded. Or what other solutions could be.
